[package]
name = "hyper-openssl"
version = "0.3.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Hyper SSL support via OpenSSL"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/hyper-openssl"
documentation = "https://docs.rs/hyper-openssl/0.3.0/hyper_openssl"
readme = "README.md"
exclude = ["test/*"]

[dependencies]
antidote = "1.0.0"
hyper = "0.11.0"
openssl = "0.9.10"
tokio-core = "0.1.8"
tokio-io = "0.1.2"
tokio-openssl = "0.1.3"
tokio-service = "0.1.0"
futures = "0.1.14"

[dev-dependencies]
rustls = "0.9"
webpki-roots = "0.11"

[[example]]
name = "bench"
path = "examples/bench.rs"
